[project]
name = "linux-6-12-x"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.16.0",
    "requests>=2.32.5",
]
